### ISSUE TITLE
KickListener Conditional

### ISSUE THREAD

**Issue by jztech101** [TechCavern/WaveTact#132]
Ensure that when it kicks the person who kicked it, that person is not itself.

**Comment by Pyker** [comment]
Haylee is confused. Haylee used kick. Haylee hurt herself in her confusion.

**Comment by lf-** [comment]
Steps to reproduce: 

&ircraw KICK #channel WaveTact :no reason

Result:

![ss](http://puu.sh/iF79f.png)

**Comment by GLolol** [comment]
Some notes:

1) `PircBotX network = event.getBot();` is used but `event.getBot()` is still called again later in the code.
2) All the sendKick calls are duplicated.
3) Why is the `channel != null` check needed? Pardon me if I'm misunderstanding, but kick messages will always require a channel!
4) `event.getChannel()` calls are also duplicated after assignment to a variable.

**Comment by jztech101** [comment]
@GLolol Whoops. I forgot about those. https://github.com/TechCavern/WaveTact/commit/ab160fe7acd49a6f53234be6ce1b20169935e0f3 Cleans it up ;)
