### ISSUE TITLE
Allow using the tell command on people who aren't there

### ISSUE THREAD

**Issue by lf-** [TechCavern/WaveTact#169]
Sometimes people leave and I forgot to tell them something. Therefore, I propose that the tell command lets you tell things to offline people.

**Comment by jztech101** [comment]
Tell Command will now allow the sending of Tell Messages to nickserv accounts who have 1) authed 2) spoke while authed to the bot. You must use the nickserv ACCOUNT NAME to take advantage of this. But it will allow you to send offline messages
