### ISSUE TITLE
Rolling 1d1 produces odd numbers like 7

### ISSUE THREAD

**Issue by jztech101** [TechCavern/WaveTact#239]
<>roll 1d1 = 7 ?

**Comment by s0cks** [comment]
You aren't clamping the numbers to a range I don't think

**Comment by jztech101** [comment]
Indeed it would appear you are correct

**Comment by jztech101** [comment]
@s0cks nope. lmao, after looking at code, I just had the closing parentheses in the wrong spot, so it was parsing the 1+1 as 11 instead of parsing the 1 and then adding 1 to it
