### ISSUE TITLE
Autokick ircbullying message

### ISSUE THREAD

**Issue by jztech101** [TechCavern/WaveTact#99]
When  the phrase "I feel offended by your recent action(s). Please read: http://stop-irc-bullying.eu/stop" is detected, kick!

**Comment by GLolol** [comment]
@jztech101, I feel offended by your recent action(s). Please read: http://stop-irc-bullying.eu/stop

**Comment by jztech101** [comment]
@GLolol 1) This is not IRC. 2)If you think that will stop actual bullies, you're an idiot. 3) Using it as a joke defeats the original purpose

**Comment by GLolol** [comment]
wtf how dare you call me an idiot

**Comment by GLolol** [comment]
i'm hurt

**Comment by jztech101** [comment]
Added

**Comment by jztech101** [comment]
┻━┻ ︵ ¯\ (ツ)/¯ ︵ ┻━┻ https://goo.gl/Tkb9dh
